//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.WebServis.TahakkukServis {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class SQLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState {
            get {
                return this.sQLStateField;
            }
            set {
                this.sQLStateField = value;
                this.RaisePropertyChanged("SQLState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class sqlException : exception {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class exception : throwable {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class throwable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(arazSonuc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tahakkukSonuc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class wsSonuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aciklamaField;
        
        private bool basariliField;
        
        private hata hataKoduField;
        
        private bool hataKoduFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
                this.RaisePropertyChanged("aciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool basarili {
            get {
                return this.basariliField;
            }
            set {
                this.basariliField = value;
                this.RaisePropertyChanged("basarili");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public hata hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
                this.RaisePropertyChanged("hataKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hataKoduSpecified {
            get {
                return this.hataKoduFieldSpecified;
            }
            set {
                this.hataKoduFieldSpecified = value;
                this.RaisePropertyChanged("hataKoduSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public enum hata {
        
        /// <remarks/>
        BASARILI,
        
        /// <remarks/>
        HATA0,
        
        /// <remarks/>
        HATA1,
        
        /// <remarks/>
        HATA2,
        
        /// <remarks/>
        HATA3,
        
        /// <remarks/>
        HATA4,
        
        /// <remarks/>
        HATA5,
        
        /// <remarks/>
        HATA6,
        
        /// <remarks/>
        HATA7,
        
        /// <remarks/>
        HATA8,
        
        /// <remarks/>
        HATA9,
        
        /// <remarks/>
        HATA10,
        
        /// <remarks/>
        HATA11,
        
        /// <remarks/>
        HATA12,
        
        /// <remarks/>
        HATA13,
        
        /// <remarks/>
        HATA14,
        
        /// <remarks/>
        HATA15,
        
        /// <remarks/>
        HATA16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class arazSonuc : wsSonuc {
        
        private string borcIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string borcID {
            get {
                return this.borcIDField;
            }
            set {
                this.borcIDField = value;
                this.RaisePropertyChanged("borcID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class tahakkukSonuc : wsSonuc {
        
        private string tahakkukIdField;
        
        private string tahakkukKdvIdField;
        
        private string tahakkukNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tahakkukId {
            get {
                return this.tahakkukIdField;
            }
            set {
                this.tahakkukIdField = value;
                this.RaisePropertyChanged("tahakkukId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tahakkukKdvId {
            get {
                return this.tahakkukKdvIdField;
            }
            set {
                this.tahakkukKdvIdField = value;
                this.RaisePropertyChanged("tahakkukKdvId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tahakkukNo {
            get {
                return this.tahakkukNoField;
            }
            set {
                this.tahakkukNoField = value;
                this.RaisePropertyChanged("tahakkukNo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class kullanici : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int kulNoField;
        
        private string sifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int kulNo {
            get {
                return this.kulNoField;
            }
            set {
                this.kulNoField = value;
                this.RaisePropertyChanged("kulNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
                this.RaisePropertyChanged("sifre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", ConfigurationName="TahakkukServis.TahakkukWs")]
    public interface TahakkukWs {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/tahakkukOlusturRequest", ReplyAction="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/tahakkukOlusturResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Framework.WebServis.TahakkukServis.SQLException), Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/tahakkukOlustur/Fault/SQ" +
            "LException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsSonuc))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Framework.WebServis.TahakkukServis.tahakkukOlusturResponse tahakkukOlustur(Framework.WebServis.TahakkukServis.tahakkukOlusturRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/tahakkukOlusturRequest", ReplyAction="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/tahakkukOlusturResponse")]
        System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.tahakkukOlusturResponse> tahakkukOlusturAsync(Framework.WebServis.TahakkukServis.tahakkukOlusturRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/tahakkukOlusturKdvliRequ" +
            "est", ReplyAction="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/tahakkukOlusturKdvliResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Framework.WebServis.TahakkukServis.SQLException), Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/tahakkukOlusturKdvli/Fau" +
            "lt/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsSonuc))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliResponse tahakkukOlusturKdvli(Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/tahakkukOlusturKdvliRequ" +
            "est", ReplyAction="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/tahakkukOlusturKdvliResp" +
            "onse")]
        System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliResponse> tahakkukOlusturKdvliAsync(Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/TahakkukSorgulaRequest", ReplyAction="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/TahakkukSorgulaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Framework.WebServis.TahakkukServis.SQLException), Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/TahakkukSorgula/Fault/SQ" +
            "LException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsSonuc))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Framework.WebServis.TahakkukServis.TahakkukSorgulaResponse TahakkukSorgula(Framework.WebServis.TahakkukServis.TahakkukSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/TahakkukSorgulaRequest", ReplyAction="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/TahakkukSorgulaResponse")]
        System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.TahakkukSorgulaResponse> TahakkukSorgulaAsync(Framework.WebServis.TahakkukServis.TahakkukSorgulaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/BorcIptalRequest", ReplyAction="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/BorcIptalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Framework.WebServis.TahakkukServis.SQLException), Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/BorcIptal/Fault/SQLExcep" +
            "tion", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsSonuc))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Framework.WebServis.TahakkukServis.BorcIptalResponse BorcIptal(Framework.WebServis.TahakkukServis.BorcIptalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/BorcIptalRequest", ReplyAction="http://ws.tahakkuk.misservices.indbilisim.com/TahakkukWs/BorcIptalResponse")]
        System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.BorcIptalResponse> BorcIptalAsync(Framework.WebServis.TahakkukServis.BorcIptalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tahakkukOlustur", WrapperNamespace="http://ws.tahakkuk.misservices.indbilisim.com/", IsWrapped=true)]
    public partial class tahakkukOlusturRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Framework.WebServis.TahakkukServis.kullanici kullanici;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sicilNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int gelirId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int borcYili;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int taksit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sonOdemeTarihi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double tutar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aciklama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int modulGrup;
        
        public tahakkukOlusturRequest() {
        }
        
        public tahakkukOlusturRequest(Framework.WebServis.TahakkukServis.kullanici kullanici, int sicilNo, int gelirId, int borcYili, int taksit, string sonOdemeTarihi, double tutar, string aciklama, int modulGrup) {
            this.kullanici = kullanici;
            this.sicilNo = sicilNo;
            this.gelirId = gelirId;
            this.borcYili = borcYili;
            this.taksit = taksit;
            this.sonOdemeTarihi = sonOdemeTarihi;
            this.tutar = tutar;
            this.aciklama = aciklama;
            this.modulGrup = modulGrup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tahakkukOlusturResponse", WrapperNamespace="http://ws.tahakkuk.misservices.indbilisim.com/", IsWrapped=true)]
    public partial class tahakkukOlusturResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Framework.WebServis.TahakkukServis.tahakkukSonuc @return;
        
        public tahakkukOlusturResponse() {
        }
        
        public tahakkukOlusturResponse(Framework.WebServis.TahakkukServis.tahakkukSonuc @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tahakkukOlusturKdvli", WrapperNamespace="http://ws.tahakkuk.misservices.indbilisim.com/", IsWrapped=true)]
    public partial class tahakkukOlusturKdvliRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Framework.WebServis.TahakkukServis.kullanici kullanici;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sicilNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int gelirId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int kdvgelirId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int borcYili;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int taksit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sonOdemeTarihi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double tutar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aciklama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int modulGrup;
        
        public tahakkukOlusturKdvliRequest() {
        }
        
        public tahakkukOlusturKdvliRequest(Framework.WebServis.TahakkukServis.kullanici kullanici, int sicilNo, int gelirId, int kdvgelirId, int borcYili, int taksit, string sonOdemeTarihi, double tutar, string aciklama, int modulGrup) {
            this.kullanici = kullanici;
            this.sicilNo = sicilNo;
            this.gelirId = gelirId;
            this.kdvgelirId = kdvgelirId;
            this.borcYili = borcYili;
            this.taksit = taksit;
            this.sonOdemeTarihi = sonOdemeTarihi;
            this.tutar = tutar;
            this.aciklama = aciklama;
            this.modulGrup = modulGrup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tahakkukOlusturKdvliResponse", WrapperNamespace="http://ws.tahakkuk.misservices.indbilisim.com/", IsWrapped=true)]
    public partial class tahakkukOlusturKdvliResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Framework.WebServis.TahakkukServis.tahakkukSonuc @return;
        
        public tahakkukOlusturKdvliResponse() {
        }
        
        public tahakkukOlusturKdvliResponse(Framework.WebServis.TahakkukServis.tahakkukSonuc @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class tahakkukBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string adiField;
        
        private double arazTutarField;
        
        private bool arazTutarFieldSpecified;
        
        private double bakiyeField;
        
        private bool bakiyeFieldSpecified;
        
        private string borcIdField;
        
        private hata hataField;
        
        private bool hataFieldSpecified;
        
        private int makbuzNoField;
        
        private int modulGrupField;
        
        private int sicilNoField;
        
        private string soyAdiField;
        
        private date thkTarField;
        
        private double thkTutarField;
        
        private bool thkTutarFieldSpecified;
        
        private date thsTarField;
        
        private double thsToplamField;
        
        private string tipField;
        
        private string turKodField;
        
        private date vadeTarField;
        
        private int vezneNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
                this.RaisePropertyChanged("adi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double arazTutar {
            get {
                return this.arazTutarField;
            }
            set {
                this.arazTutarField = value;
                this.RaisePropertyChanged("arazTutar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arazTutarSpecified {
            get {
                return this.arazTutarFieldSpecified;
            }
            set {
                this.arazTutarFieldSpecified = value;
                this.RaisePropertyChanged("arazTutarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double bakiye {
            get {
                return this.bakiyeField;
            }
            set {
                this.bakiyeField = value;
                this.RaisePropertyChanged("bakiye");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bakiyeSpecified {
            get {
                return this.bakiyeFieldSpecified;
            }
            set {
                this.bakiyeFieldSpecified = value;
                this.RaisePropertyChanged("bakiyeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string borcId {
            get {
                return this.borcIdField;
            }
            set {
                this.borcIdField = value;
                this.RaisePropertyChanged("borcId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public hata hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
                this.RaisePropertyChanged("hata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hataSpecified {
            get {
                return this.hataFieldSpecified;
            }
            set {
                this.hataFieldSpecified = value;
                this.RaisePropertyChanged("hataSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int makbuzNo {
            get {
                return this.makbuzNoField;
            }
            set {
                this.makbuzNoField = value;
                this.RaisePropertyChanged("makbuzNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int modulGrup {
            get {
                return this.modulGrupField;
            }
            set {
                this.modulGrupField = value;
                this.RaisePropertyChanged("modulGrup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int sicilNo {
            get {
                return this.sicilNoField;
            }
            set {
                this.sicilNoField = value;
                this.RaisePropertyChanged("sicilNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string soyAdi {
            get {
                return this.soyAdiField;
            }
            set {
                this.soyAdiField = value;
                this.RaisePropertyChanged("soyAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public date thkTar {
            get {
                return this.thkTarField;
            }
            set {
                this.thkTarField = value;
                this.RaisePropertyChanged("thkTar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double thkTutar {
            get {
                return this.thkTutarField;
            }
            set {
                this.thkTutarField = value;
                this.RaisePropertyChanged("thkTutar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool thkTutarSpecified {
            get {
                return this.thkTutarFieldSpecified;
            }
            set {
                this.thkTutarFieldSpecified = value;
                this.RaisePropertyChanged("thkTutarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public date thsTar {
            get {
                return this.thsTarField;
            }
            set {
                this.thsTarField = value;
                this.RaisePropertyChanged("thsTar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double thsToplam {
            get {
                return this.thsToplamField;
            }
            set {
                this.thsToplamField = value;
                this.RaisePropertyChanged("thsToplam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string tip {
            get {
                return this.tipField;
            }
            set {
                this.tipField = value;
                this.RaisePropertyChanged("tip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string turKod {
            get {
                return this.turKodField;
            }
            set {
                this.turKodField = value;
                this.RaisePropertyChanged("turKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public date vadeTar {
            get {
                return this.vadeTarField;
            }
            set {
                this.vadeTarField = value;
                this.RaisePropertyChanged("vadeTar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int vezneNo {
            get {
                return this.vezneNoField;
            }
            set {
                this.vezneNoField = value;
                this.RaisePropertyChanged("vezneNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TahakkukSorgula", WrapperNamespace="http://ws.tahakkuk.misservices.indbilisim.com/", IsWrapped=true)]
    public partial class TahakkukSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Framework.WebServis.TahakkukServis.kullanici kullanici;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string borcId;
        
        public TahakkukSorgulaRequest() {
        }
        
        public TahakkukSorgulaRequest(Framework.WebServis.TahakkukServis.kullanici kullanici, string borcId) {
            this.kullanici = kullanici;
            this.borcId = borcId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TahakkukSorgulaResponse", WrapperNamespace="http://ws.tahakkuk.misservices.indbilisim.com/", IsWrapped=true)]
    public partial class TahakkukSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Framework.WebServis.TahakkukServis.tahakkukBean @return;
        
        public TahakkukSorgulaResponse() {
        }
        
        public TahakkukSorgulaResponse(Framework.WebServis.TahakkukServis.tahakkukBean @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BorcIptal", WrapperNamespace="http://ws.tahakkuk.misservices.indbilisim.com/", IsWrapped=true)]
    public partial class BorcIptalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Framework.WebServis.TahakkukServis.kullanici kullanici;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string borcId;
        
        public BorcIptalRequest() {
        }
        
        public BorcIptalRequest(Framework.WebServis.TahakkukServis.kullanici kullanici, string borcId) {
            this.kullanici = kullanici;
            this.borcId = borcId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BorcIptalResponse", WrapperNamespace="http://ws.tahakkuk.misservices.indbilisim.com/", IsWrapped=true)]
    public partial class BorcIptalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tahakkuk.misservices.indbilisim.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Framework.WebServis.TahakkukServis.arazSonuc @return;
        
        public BorcIptalResponse() {
        }
        
        public BorcIptalResponse(Framework.WebServis.TahakkukServis.arazSonuc @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TahakkukWsChannel : Framework.WebServis.TahakkukServis.TahakkukWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TahakkukWsClient : System.ServiceModel.ClientBase<Framework.WebServis.TahakkukServis.TahakkukWs>, Framework.WebServis.TahakkukServis.TahakkukWs {
        
        public TahakkukWsClient() {
        }
        
        public TahakkukWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TahakkukWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TahakkukWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TahakkukWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.WebServis.TahakkukServis.tahakkukOlusturResponse Framework.WebServis.TahakkukServis.TahakkukWs.tahakkukOlustur(Framework.WebServis.TahakkukServis.tahakkukOlusturRequest request) {
            return base.Channel.tahakkukOlustur(request);
        }
        
        public Framework.WebServis.TahakkukServis.tahakkukSonuc tahakkukOlustur(Framework.WebServis.TahakkukServis.kullanici kullanici, int sicilNo, int gelirId, int borcYili, int taksit, string sonOdemeTarihi, double tutar, string aciklama, int modulGrup) {
            Framework.WebServis.TahakkukServis.tahakkukOlusturRequest inValue = new Framework.WebServis.TahakkukServis.tahakkukOlusturRequest();
            inValue.kullanici = kullanici;
            inValue.sicilNo = sicilNo;
            inValue.gelirId = gelirId;
            inValue.borcYili = borcYili;
            inValue.taksit = taksit;
            inValue.sonOdemeTarihi = sonOdemeTarihi;
            inValue.tutar = tutar;
            inValue.aciklama = aciklama;
            inValue.modulGrup = modulGrup;
            Framework.WebServis.TahakkukServis.tahakkukOlusturResponse retVal = ((Framework.WebServis.TahakkukServis.TahakkukWs)(this)).tahakkukOlustur(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.tahakkukOlusturResponse> Framework.WebServis.TahakkukServis.TahakkukWs.tahakkukOlusturAsync(Framework.WebServis.TahakkukServis.tahakkukOlusturRequest request) {
            return base.Channel.tahakkukOlusturAsync(request);
        }
        
        public System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.tahakkukOlusturResponse> tahakkukOlusturAsync(Framework.WebServis.TahakkukServis.kullanici kullanici, int sicilNo, int gelirId, int borcYili, int taksit, string sonOdemeTarihi, double tutar, string aciklama, int modulGrup) {
            Framework.WebServis.TahakkukServis.tahakkukOlusturRequest inValue = new Framework.WebServis.TahakkukServis.tahakkukOlusturRequest();
            inValue.kullanici = kullanici;
            inValue.sicilNo = sicilNo;
            inValue.gelirId = gelirId;
            inValue.borcYili = borcYili;
            inValue.taksit = taksit;
            inValue.sonOdemeTarihi = sonOdemeTarihi;
            inValue.tutar = tutar;
            inValue.aciklama = aciklama;
            inValue.modulGrup = modulGrup;
            return ((Framework.WebServis.TahakkukServis.TahakkukWs)(this)).tahakkukOlusturAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliResponse Framework.WebServis.TahakkukServis.TahakkukWs.tahakkukOlusturKdvli(Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliRequest request) {
            return base.Channel.tahakkukOlusturKdvli(request);
        }
        
        public Framework.WebServis.TahakkukServis.tahakkukSonuc tahakkukOlusturKdvli(Framework.WebServis.TahakkukServis.kullanici kullanici, int sicilNo, int gelirId, int kdvgelirId, int borcYili, int taksit, string sonOdemeTarihi, double tutar, string aciklama, int modulGrup) {
            Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliRequest inValue = new Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliRequest();
            inValue.kullanici = kullanici;
            inValue.sicilNo = sicilNo;
            inValue.gelirId = gelirId;
            inValue.kdvgelirId = kdvgelirId;
            inValue.borcYili = borcYili;
            inValue.taksit = taksit;
            inValue.sonOdemeTarihi = sonOdemeTarihi;
            inValue.tutar = tutar;
            inValue.aciklama = aciklama;
            inValue.modulGrup = modulGrup;
            Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliResponse retVal = ((Framework.WebServis.TahakkukServis.TahakkukWs)(this)).tahakkukOlusturKdvli(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliResponse> Framework.WebServis.TahakkukServis.TahakkukWs.tahakkukOlusturKdvliAsync(Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliRequest request) {
            return base.Channel.tahakkukOlusturKdvliAsync(request);
        }
        
        public System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliResponse> tahakkukOlusturKdvliAsync(Framework.WebServis.TahakkukServis.kullanici kullanici, int sicilNo, int gelirId, int kdvgelirId, int borcYili, int taksit, string sonOdemeTarihi, double tutar, string aciklama, int modulGrup) {
            Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliRequest inValue = new Framework.WebServis.TahakkukServis.tahakkukOlusturKdvliRequest();
            inValue.kullanici = kullanici;
            inValue.sicilNo = sicilNo;
            inValue.gelirId = gelirId;
            inValue.kdvgelirId = kdvgelirId;
            inValue.borcYili = borcYili;
            inValue.taksit = taksit;
            inValue.sonOdemeTarihi = sonOdemeTarihi;
            inValue.tutar = tutar;
            inValue.aciklama = aciklama;
            inValue.modulGrup = modulGrup;
            return ((Framework.WebServis.TahakkukServis.TahakkukWs)(this)).tahakkukOlusturKdvliAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.WebServis.TahakkukServis.TahakkukSorgulaResponse Framework.WebServis.TahakkukServis.TahakkukWs.TahakkukSorgula(Framework.WebServis.TahakkukServis.TahakkukSorgulaRequest request) {
            return base.Channel.TahakkukSorgula(request);
        }
        
        public Framework.WebServis.TahakkukServis.tahakkukBean TahakkukSorgula(Framework.WebServis.TahakkukServis.kullanici kullanici, string borcId) {
            Framework.WebServis.TahakkukServis.TahakkukSorgulaRequest inValue = new Framework.WebServis.TahakkukServis.TahakkukSorgulaRequest();
            inValue.kullanici = kullanici;
            inValue.borcId = borcId;
            Framework.WebServis.TahakkukServis.TahakkukSorgulaResponse retVal = ((Framework.WebServis.TahakkukServis.TahakkukWs)(this)).TahakkukSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.TahakkukSorgulaResponse> Framework.WebServis.TahakkukServis.TahakkukWs.TahakkukSorgulaAsync(Framework.WebServis.TahakkukServis.TahakkukSorgulaRequest request) {
            return base.Channel.TahakkukSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.TahakkukSorgulaResponse> TahakkukSorgulaAsync(Framework.WebServis.TahakkukServis.kullanici kullanici, string borcId) {
            Framework.WebServis.TahakkukServis.TahakkukSorgulaRequest inValue = new Framework.WebServis.TahakkukServis.TahakkukSorgulaRequest();
            inValue.kullanici = kullanici;
            inValue.borcId = borcId;
            return ((Framework.WebServis.TahakkukServis.TahakkukWs)(this)).TahakkukSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.WebServis.TahakkukServis.BorcIptalResponse Framework.WebServis.TahakkukServis.TahakkukWs.BorcIptal(Framework.WebServis.TahakkukServis.BorcIptalRequest request) {
            return base.Channel.BorcIptal(request);
        }
        
        public Framework.WebServis.TahakkukServis.arazSonuc BorcIptal(Framework.WebServis.TahakkukServis.kullanici kullanici, string borcId) {
            Framework.WebServis.TahakkukServis.BorcIptalRequest inValue = new Framework.WebServis.TahakkukServis.BorcIptalRequest();
            inValue.kullanici = kullanici;
            inValue.borcId = borcId;
            Framework.WebServis.TahakkukServis.BorcIptalResponse retVal = ((Framework.WebServis.TahakkukServis.TahakkukWs)(this)).BorcIptal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.BorcIptalResponse> Framework.WebServis.TahakkukServis.TahakkukWs.BorcIptalAsync(Framework.WebServis.TahakkukServis.BorcIptalRequest request) {
            return base.Channel.BorcIptalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Framework.WebServis.TahakkukServis.BorcIptalResponse> BorcIptalAsync(Framework.WebServis.TahakkukServis.kullanici kullanici, string borcId) {
            Framework.WebServis.TahakkukServis.BorcIptalRequest inValue = new Framework.WebServis.TahakkukServis.BorcIptalRequest();
            inValue.kullanici = kullanici;
            inValue.borcId = borcId;
            return ((Framework.WebServis.TahakkukServis.TahakkukWs)(this)).BorcIptalAsync(inValue);
        }
    }
}
