//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.WebUI.TahsilatService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tahsilat", Namespace="http://schemas.datacontract.org/2004/07/Cls.Model")]
    [System.SerializableAttribute()]
    public partial class Tahsilat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AzaltanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GenelToplamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MakbuzNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OdemeTarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OdenenTutarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TahakkukNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TahakkukTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TahakukTutarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VezneNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Artan {
            get {
                return this.ArtanField;
            }
            set {
                if ((this.ArtanField.Equals(value) != true)) {
                    this.ArtanField = value;
                    this.RaisePropertyChanged("Artan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Azaltan {
            get {
                return this.AzaltanField;
            }
            set {
                if ((this.AzaltanField.Equals(value) != true)) {
                    this.AzaltanField = value;
                    this.RaisePropertyChanged("Azaltan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GenelToplam {
            get {
                return this.GenelToplamField;
            }
            set {
                if ((this.GenelToplamField.Equals(value) != true)) {
                    this.GenelToplamField = value;
                    this.RaisePropertyChanged("GenelToplam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MakbuzNo {
            get {
                return this.MakbuzNoField;
            }
            set {
                if ((this.MakbuzNoField.Equals(value) != true)) {
                    this.MakbuzNoField = value;
                    this.RaisePropertyChanged("MakbuzNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OdemeTar {
            get {
                return this.OdemeTarField;
            }
            set {
                if ((this.OdemeTarField.Equals(value) != true)) {
                    this.OdemeTarField = value;
                    this.RaisePropertyChanged("OdemeTar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OdenenTutar {
            get {
                return this.OdenenTutarField;
            }
            set {
                if ((this.OdenenTutarField.Equals(value) != true)) {
                    this.OdenenTutarField = value;
                    this.RaisePropertyChanged("OdenenTutar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sonuc {
            get {
                return this.SonucField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucField, value) != true)) {
                    this.SonucField = value;
                    this.RaisePropertyChanged("Sonuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TahakkukNo {
            get {
                return this.TahakkukNoField;
            }
            set {
                if ((this.TahakkukNoField.Equals(value) != true)) {
                    this.TahakkukNoField = value;
                    this.RaisePropertyChanged("TahakkukNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TahakkukTarihi {
            get {
                return this.TahakkukTarihiField;
            }
            set {
                if ((this.TahakkukTarihiField.Equals(value) != true)) {
                    this.TahakkukTarihiField = value;
                    this.RaisePropertyChanged("TahakkukTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TahakukTutar {
            get {
                return this.TahakukTutarField;
            }
            set {
                if ((this.TahakukTutarField.Equals(value) != true)) {
                    this.TahakukTutarField = value;
                    this.RaisePropertyChanged("TahakukTutar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VezneNo {
            get {
                return this.VezneNoField;
            }
            set {
                if ((this.VezneNoField.Equals(value) != true)) {
                    this.VezneNoField = value;
                    this.RaisePropertyChanged("VezneNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TahsilatService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TahsilatSorgula", ReplyAction="http://tempuri.org/IService/TahsilatSorgulaResponse")]
        Framework.WebUI.TahsilatService.Tahsilat[] TahsilatSorgula(string sequenceNo, int sicilNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TahsilatSorgula", ReplyAction="http://tempuri.org/IService/TahsilatSorgulaResponse")]
        System.Threading.Tasks.Task<Framework.WebUI.TahsilatService.Tahsilat[]> TahsilatSorgulaAsync(string sequenceNo, int sicilNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Framework.WebUI.TahsilatService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Framework.WebUI.TahsilatService.IService>, Framework.WebUI.TahsilatService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Framework.WebUI.TahsilatService.Tahsilat[] TahsilatSorgula(string sequenceNo, int sicilNo) {
            return base.Channel.TahsilatSorgula(sequenceNo, sicilNo);
        }
        
        public System.Threading.Tasks.Task<Framework.WebUI.TahsilatService.Tahsilat[]> TahsilatSorgulaAsync(string sequenceNo, int sicilNo) {
            return base.Channel.TahsilatSorgulaAsync(sequenceNo, sicilNo);
        }
    }
}
